apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: rafaxzx/api:dev
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: api-config # ConfigMap para variáveis de ambiente
