apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'api'
        static_configs:
          - targets: ['api-service:58745']
      - job_name: 'worker'
        static_configs:
          - targets: ['worker-service:80']
