apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672 # Porta do RabbitMQ
      targetPort: 5672
    - protocol: TCP
      port: 15672 # Porta de gerenciamento (dashboard RabbitMQ)
      targetPort: 15672
  type: ClusterIP
