apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-config
  labels:
    app: worker
data:
  RabbitMQ__Host: "rabbitmq-service"
  RabbitMQ__QueueName: "contacts-queue"
  Logging__LogLevel__Default: "Information"
