apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker-container
          image: rafaxzx/workermessageconsumer:latest
          envFrom:
            - configMapRef:
                name: worker-config # ConfigMap para o Worker
          ports:
            - containerPort: 80
